---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-2.7
  commands:
  - docker build -t nephatrine/docker-registry:2.7 .
  - HOME=/mnt/config/home docker push nephatrine/docker-registry:2.7
- name: build-latest
  commands:
  - docker tag nephatrine/docker-registry:2.7 pdr.nephatrine.net/nephatrine/docker-registry:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/docker-registry:latest
  - docker tag pdr.nephatrine.net/nephatrine/docker-registry:latest nephatrine/docker-registry:latest
  - HOME=/mnt/config/home docker push nephatrine/docker-registry:latest
  - docker rmi pdr.nephatrine.net/nephatrine/docker-registry:latest
  depends_on:
  - build-2.7

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: b6dbf8ecf2e6959e7c5b42f0ad00850a0469ceb2ca856d9d44e81e8e1bd0f18b

...
