---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/docker-registry:testing .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/docker-registry:testing
  - docker tag pdr.nephatrine.net/nephatrine/docker-registry:testing nephatrine/docker-registry:testing
  - HOME=/mnt/config/home docker push nephatrine/docker-registry:testing
  - docker rmi pdr.nephatrine.net/nephatrine/docker-registry:testing

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 86b79308f373e86379e2521afaf9d6eb3d7a18a1193388d569527b17c97985b4

...
