---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - docker build --pull -t pdr.nephatrine.net/nephatrine/docker-registry:latest .
  - docker push pdr.nephatrine.net/nephatrine/docker-registry:latest
  - docker tag pdr.nephatrine.net/nephatrine/docker-registry:latest nephatrine/docker-registry:latest
  - docker push nephatrine/docker-registry:latest

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://files.nephatrine.net/Images/Buttons/Drone.png
    message: "Automated build of **{{repo.name}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: webhook-id
    webhook_token:
      from_secret: webhook-token

depends_on:
- default