#!/usr/bin/with-contenv bash

if [[ ! -e /mnt/config/etc/registry/config.yml ]]; then
  if [[ ! -d /mnt/config/etc/registry ]]; then
    s6-setuidgid guardian mkdir -p /mnt/config/etc/registry
  fi

  s6-setuidgid guardian cp -n /etc/registry/* /mnt/config/etc/registry/
fi

if [[ ! -d ${REGISTRY_DATA_DIR} ]]; then
  s6-setuidgid guardian mkdir -p ${REGISTRY_DATA_DIR}
fi
